version: "3"
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./api/:/app/api/
      - ./checkpoints/:/app/checkpoints/
      - ./dataloading/:/app/dataloading/
      - ./models/:/app/models/
    ports:
      - "80:80"
